config/routes.rb
Rails.application.routes.draw do
 
  get 'users/new'
  root 'pages#homepage'
  get 'about' => 'pages#about'
  
  resources :articles do 
    resources :comments
  end
  
  mount ActionCable.server => '/cable'
  
  get 'signup' , to: 'users#new'
  # post 'users', to: 'users#create'
  # or 
  resources :users, except: [:new]
  
  get 'login' , to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
end

app/views/shared/_article.html.erb
 <% obj.each do |a| %>
 <div class="row">
     <div class="col-xs-8 col-xs-offset-2">
         <div class="well well-lg">
             <div class="article-title"> 
             <%= link_to a.title , article_path(a) %>
             </div>
             <div class="article-body">
               <%= truncate(a.description, length: 100) %>
               <div class="article-meta-details">
                 <small>
                     Created by: <%= a.user.username %> , 
                     <%= time_ago_in_words a.created_at %> ago,
                     last updated: <%= time_ago_in_words a.updated_at %> ago
                 </small>
               </div>
             </div>   
             <% if a.categories.any? %>
               <p>Categories: <%= render a.categories %>  </p>
             <%end%>
             <% if logged_in? && (current_user == a.user || current_user.admin?  )%>
                <div class="article-actions">
                   <%= link_to "Delete", article_path(a), method: :delete, 
                   data: {confirm: "Are you sure you want to delete the article?"}, 
                   class: 'btn btn-xs btn-danger' %>
                   <%= link_to "Edit", edit_article_path(a), class: 'btn btn-xs btn-success'%>
                </div>
             <%end%>
         </div>
     </div>
 </div>

<%end%>

app/views/shared/_error_form_messaging.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %> prohibited the <%= obj.class.name%> from being saved:
                    </h2>
                    <div class="panel-body">    
                        <ul>     
                            <% obj.errors.full_messages.each do |msg| %>
                                
                            <li>
                                <%= msg %>
                            </li>
                                 <% end %>
                        </ul>                                         
                    </div>
                </div>
            </div>
        </div>
    </div>   
<% end %> 

app/views/shared/_flash_error_messaging.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%=name%>'>
                <a href="#" class="close" data-dismiss="alert">×</a>
                 <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <%end%>    
    </div>
</div>
      

app/views/shared/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small class="pull-left">Copyright &copy by Izak Tarashandegan</small>
        <nav>
            <ul class="pull-right">
                <li><%=link_to "About", about_path %></li> 
                
            </ul>
        </nav>    
    </footer>
</div>

app/views/shared/_listing_categories.html.erb
<% Category.all.each do |category| %>
  <li>
      <%= link_to category.name, category_path(category) %>
  </li> 
<% end %>
<% if logged_in? and current_user.admin? %>
    <li role="separator" class="divider"></li>
    <li>
        <%= link_to 'Create New Category', new_category_path %>
    </li>
<% end %>

app/views/shared/_menu.html.erb
    <%= link_to "Home", root_path %> |
    <%= link_to "About", about_path %> |
    <%= link_to "Alpha Blog ", articles_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: 'navbar-brand', id: "logo" %>
    </div>

 <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">         
        <li>
            <%= link_to "Articles", articles_path %>
        </li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <%end%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Categories", categories_path %></li>
              <%= render 'shared/listing_categories'%>
            </ul>
          </li>
      </ul>
      <!--<form class="navbar-form navbar-left">-->
      <!--  <div class="form-group">-->
      <!--    <input type="text" class="form-control" placeholder="Search">-->
      <!--  </div>-->
      <!--  <button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in?%>
        <li>
          <%= link_to "Log out", logout_path, method: :delete %> 
        </li>         
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>&nbspProfile            
              <%= admin?(current_user) %>                     
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View your profile", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
         <% else %>
           <li><%= link_to "Log in", login_path , class:'lable label-primary' %> </li> 
           <li><%= link_to "Sign up", signup_path %> </li> 
         <%end%>
         
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_user-info.html.erb
<ul class="listing">
    <div class="row">
        <div class="well col-md-4 col-md-offset-4">
            <li>
                <%= link_to gravatar_for(obj), user_path(obj) %>                   
            </li>
            <li>
                  <%=  link_to obj.username, user_path(obj) %> 
            </li>
            <li>
                <small>
                    <%= pluralize(obj.articles.count, "article") if obj.articles %>
                </small>
            </li>
            <li>
                <% if logged_in? && current_user.admin? %>
                    <%= link_to 'Delete an User', 
                             user_path(obj), 
                             method: :delete,
                             data: { confirm: 'Are you sure you want to delete the user and all its articles?' },
                             class: 'btn btn-danger'%> 
                <% end %>
            </li>
        </div>
    </div>
</ul>    